
import waf_util
import mfcuke

@waf_util.chdirdecorator
def generate(ctx):

    fname = waf_util.get_all_scenarios()['scenario021']
    mfcuke.run_scenario_filename(fname, short_run=waf_util.is_short_run())

